const Announcement = require('../models/Announcement');
const Event = require('../models/Event');
const User = require('../models/User');

const MINUTE_MS = 60 * 1000;

function parsePositiveInt(envName, fallback) {
  const value = parseInt(process.env[envName] || String(fallback), 10);
  return Number.isFinite(value) && value > 0 ? value : fallback;
}

function getEventCompletionDate(event) {
  const rawValue = event?.endDate || event?.startDate || null;
  if (!rawValue) return null;

  const parsed = new Date(rawValue);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}

function isEventExpired(event, nowDate = new Date()) {
  const completionDate = getEventCompletionDate(event);
  if (!completionDate) return false;
  return completionDate.getTime() <= nowDate.getTime();
}

function buildActiveEventsQuery(nowDate = new Date()) {
  return {
    $or: [
      { endDate: { $gt: nowDate } },
      { endDate: null, startDate: { $gt: nowDate } },
      { endDate: { $exists: false }, startDate: { $gt: nowDate } },
    ],
  };
}

function buildExpiredEventsQuery(nowDate = new Date()) {
  return {
    $expr: {
      $lte: [
        { $ifNull: ['$endDate', '$startDate'] },
        nowDate,
      ],
    },
  };
}

async function resolveAnnouncementAuthorId(event) {
  if (event?.createdBy) return event.createdBy;

  const fallbackAdmin = await User.findOne({
    role: { $in: ['super_admin', 'admin', 'hr', 'alumni_officer'] },
    status: 'approved',
    isDeleted: { $ne: true },
  })
    .select('_id')
    .sort({ approvedAt: 1, createdAt: 1 })
    .lean();

  if (fallbackAdmin?._id) return fallbackAdmin._id;

  const fallbackUser = await User.findOne({
    status: 'approved',
    isDeleted: { $ne: true },
  })
    .select('_id')
    .sort({ approvedAt: 1, createdAt: 1 })
    .lean();

  return fallbackUser?._id || null;
}

function formatCompletionMessage(event, completionDate) {
  const title = String(event?.title || 'Untitled event').trim() || 'Untitled event';
  const formattedDate = completionDate.toLocaleString();

  return {
    title: `Event completed: ${title}`,
    content: `The event "${title}" ended on ${formattedDate} and has been automatically removed from the Events page. Thank you to everyone who participated.`,
    category: 'Company News',
  };
}

async function ensureCompletionAnnouncement(event, nowDate = new Date()) {
  const systemKey = `event-completed:${String(event?._id || '')}`;
  if (!systemKey || systemKey.endsWith(':')) return null;

  const existing = await Announcement.findOne({ systemKey }).select('_id').lean();
  if (existing?._id) return existing._id;

  const authorId = await resolveAnnouncementAuthorId(event);
  if (!authorId) {
    console.warn('[events] Skipping completion announcement because no author could be resolved for event', String(event?._id || 'unknown'));
    return null;
  }

  const completionDate = getEventCompletionDate(event) || nowDate;
  const message = formatCompletionMessage(event, completionDate);

  const announcement = await Announcement.create({
    author: authorId,
    title: message.title,
    content: message.content,
    category: message.category,
    autoGenerated: true,
    sourceType: 'event',
    sourceId: event._id,
    systemKey,
  });

  return announcement._id;
}

async function processExpiredEvent(event, reason = 'scheduled', nowDate = new Date()) {
  if (!event?._id || !isEventExpired(event, nowDate)) {
    return { eventId: String(event?._id || ''), deleted: false, notificationCreated: false, reason };
  }

  const announcementId = await ensureCompletionAnnouncement(event, nowDate);
  const deleteResult = await Event.deleteOne({ _id: event._id });

  return {
    eventId: String(event._id),
    deleted: Number(deleteResult?.deletedCount || 0) > 0,
    notificationCreated: Boolean(announcementId),
    reason,
  };
}

async function cleanupExpiredEvents(reason = 'scheduled') {
  const nowDate = new Date();
  const expiredEvents = await Event.find(buildExpiredEventsQuery(nowDate))
    .select('_id title startDate endDate createdBy')
    .lean();

  if (!expiredEvents.length) {
    return {
      reason,
      expiredEvents: 0,
      deletedEvents: 0,
      createdNotifications: 0,
    };
  }

  let deletedEvents = 0;
  let createdNotifications = 0;

  for (const event of expiredEvents) {
    try {
      const result = await processExpiredEvent(event, reason, nowDate);
      if (result.deleted) deletedEvents += 1;
      if (result.notificationCreated) createdNotifications += 1;
    } catch (err) {
      console.error('[events] Failed to process expired event:', String(event?._id || 'unknown'), err);
    }
  }

  const summary = {
    reason,
    expiredEvents: expiredEvents.length,
    deletedEvents,
    createdNotifications,
  };

  console.log('[events] Event lifecycle job complete:', summary);
  return summary;
}

function scheduleEventLifecycleJob() {
  const intervalMinutes = parsePositiveInt('EVENT_LIFECYCLE_JOB_INTERVAL_MINUTES', 5);
  const intervalMs = intervalMinutes * MINUTE_MS;
  const initialDelayMs = Math.min(intervalMs, 30 * 1000);

  setTimeout(() => {
    cleanupExpiredEvents('startup').catch((err) => {
      console.error('[events] Initial event lifecycle job failed:', err);
    });
  }, initialDelayMs);

  setInterval(() => {
    cleanupExpiredEvents('scheduled').catch((err) => {
      console.error('[events] Scheduled event lifecycle job failed:', err);
    });
  }, intervalMs);
}

module.exports = {
  buildActiveEventsQuery,
  cleanupExpiredEvents,
  getEventCompletionDate,
  isEventExpired,
  processExpiredEvent,
  scheduleEventLifecycleJob,
};