const mongoose = require('mongoose');

const commentSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  text: { type: String, required: true },
  createdAt: { type: Date, default: Date.now }
});

const announcementSchema = new mongoose.Schema({
  author: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  title: { type: String, default: '' },
  content: { type: String, default: '' },
  category: { type: String, default: 'Company News' },
  autoGenerated: { type: Boolean, default: false },
  sourceType: { type: String, default: undefined },
  sourceId: { type: mongoose.Schema.Types.ObjectId, default: undefined },
  systemKey: { type: String, default: undefined },
  attachments: [{
    kind: { type: String, enum: ['image', 'video'], required: true },
    url: { type: String, required: true }
  }],
  createdAt: { type: Date, default: Date.now },
  hearts: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  comments: [commentSchema]
});

announcementSchema.index({ systemKey: 1 }, { unique: true, sparse: true });

module.exports = mongoose.model('Announcement', announcementSchema);
